# Generated by Django 5.0.6 on 2026-06-10 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('store_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('store_desc', models.TextField(blank=True)),
                ('payout_method', models.CharField(default='paypal', max_length=50)),
                ('payout_account', models.CharField(blank=True, max_length=200)),
                ('min_payout', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('notify_sale', models.BooleanField(default=True)),
                ('notify_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
