# Generated by Django 5.0.6 on 2026-06-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('bestseller', 'Bestseller')], default='', max_length=20),
        ),
    ]
